-- Plain-Lua checks for lascisboard.koplugin/lbcore.lua:  lua5.1 scripts/kobo/test-lbcore.lua
package.path = "scripts/kobo/lascisboard.koplugin/?.lua;" .. package.path
local core = require("lbcore")
local n = 0
local function eq(a, b, msg)
  n = n + 1
  if a ~= b then error(("FAIL %s: expected %s, got %s"):format(msg, tostring(b), tostring(a))) end
end
eq(core.contentIdToPath("file:///mnt/onboard/Books/A%20B.epub"), "/mnt/onboard/Books/A B.epub", "decode path")
eq(core.contentIdToPath("file:///mnt/onboard/Tutsağı.epub"), "/mnt/onboard/Tutsağı.epub", "utf8 path kept")
eq(core.contentIdToPath("abc"), nil, "non-file id")
eq(core.isBookFile("x.EPUB"), true, "epub upper")
eq(core.isBookFile("x.kepub.epub"), true, "kepub")
eq(core.isBookFile(".hidden.epub"), false, "hidden")
eq(core.isBookFile("cover.jpg"), false, "jpg")
eq(core.nickelStatus(2), "complete", "nickel finished")
eq(core.nickelStatus("1"), "reading", "nickel reading")
eq(core.nickelStatus(0), nil, "nickel unread")
eq(core.nextCursor(100, 200, 1000), 200, "cursor advances")
eq(core.nextCursor(300, 200, 1000), 300, "cursor never goes back")
eq(core.nextCursor(100, 5000, 1000), 1300, "cursor capped at now+skew")
eq(core.nextCursor(100, nil, 1000), 100, "empty batch")
eq(core.readFrom(0), 0, "from zero")
eq(core.readFrom(100000), 100000 - 86400, "lookback a day")
local b = core.mergeBook({ title = "A", status = "reading" }, { title = "B", authors = "X", status = "complete" })
eq(b.title, "A", "first title wins"); eq(b.authors, "X", "gap filled"); eq(b.status, "reading", "nickel status does not override")
local c = core.mergeBook({ title = "A", status = "complete" }, { status = "reading", _sidecar = true })
eq(c.status, "reading", "sidecar status wins")
eq(core.cleanBook({ md5 = "x", _sidecar = true }).md5, "x", "clean keeps"); eq(core.cleanBook({ _sidecar = true })._sidecar, nil, "clean drops")
local t = os.time({ year = 2026, month = 10, day = 5, hour = 4, min = 59 })
eq(core.newsDue("2026-10-04", t), false, "before 05:00")
local t2 = os.time({ year = 2026, month = 10, day = 5, hour = 6 })
eq(core.newsDue("2026-10-04", t2), true, "due after 05:00")
eq(core.newsDue("2026-10-05", t2), false, "once a day")

-- news
eq(core.isNewsPath("/mnt/onboard/.adds/koreader/news/Feed.epub"), true, "default news dir")
eq(core.isNewsPath("/mnt/onboard/News/x.epub", "/mnt/onboard/News"), true, "custom news dir")
eq(core.isNewsPath("/mnt/onboard/Newsletters/x.epub", "/mnt/onboard/News"), false, "prefix is a folder, not a word")
eq(core.isNewsPath("/mnt/onboard/Books/x.epub"), false, "a book")
-- covers
eq(core.opfPathFromContainer([[<container><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>]]), "OEBPS/content.opf", "container")
local opf3 = [[<manifest><item id="c" href="images/cover.jpg" media-type="image/jpeg" properties="cover-image"/><item id="x" href="a.xhtml" media-type="application/xhtml+xml"/></manifest>]]
eq(core.coverHrefFromOpf(opf3), "images/cover.jpg", "epub3 cover-image")
local opf2 = [[<metadata><meta name="cover" content="img1"/></metadata><manifest><item href="Images/front.png" id="img1" media-type="image/png"/></manifest>]]
eq(core.coverHrefFromOpf(opf2), "Images/front.png", "epub2 meta cover")
local opf_guess = [[<manifest><item id="p1" href="p1.jpg" media-type="image/jpeg"/><item id="cover-img" href="img/c.jpeg" media-type="image/jpeg"/></manifest>]]
eq(core.coverHrefFromOpf(opf_guess), "img/c.jpeg", "named cover image")
eq(core.coverHrefFromOpf([[<manifest><item id="a" href="a.xhtml" media-type="application/xhtml+xml"/></manifest>]]), nil, "no image")
eq(core.resolveZipPath("OEBPS/content.opf", "images/c.jpg"), "OEBPS/images/c.jpg", "relative")
eq(core.resolveZipPath("OEBPS/text/content.opf", "../images/c%20d.jpg"), "OEBPS/images/c d.jpg", "dot-dot + decode")
eq(core.resolveZipPath("content.opf", "c.jpg"), "c.jpg", "opf at root")
eq(core.imageMime("x.JPG"), "image/jpeg", "mime jpg"); eq(core.imageMime("x.svg"), nil, "svg not sent")
-- settings
eq(core.settingAllowed("screensaver_type", "cover"), true, "allowed string")
eq(core.settingAllowed("auto_restore_wifi", true), true, "allowed bool")
eq(core.settingAllowed("auto_restore_wifi", "yes"), false, "wrong type refused")
eq(core.settingAllowed("ota_server", "http://evil"), false, "a key outside the catalogue is refused")
eq(core.settingAllowed("keyboard_layouts", "en"), false, "table settings are not in the allow-list")
eq(core.settingAllowed("device_id", "x"), false, "denied key")
eq(core.settingAllowed("bad key", 1), false, "bad key")
eq(core.settingAllowed("x", {}), false, "tables refused")
eq(core.settingAllowed("screensaver_message", core.NULL), true, "null = reset")
eq(core.keyKind("footer.time"), "field", "dotted = field"); eq(core.keyKind("pt:nb_cols_portrait"), "pt", "project title")
eq(core.keyKind("a.b.c"), nil, "two dots refused"); eq(core.keyKind("pt:../x"), nil, "pt path refused")
eq(core.settingAllowed("footer.time", true), true, "footer field allowed")
eq(core.settingAllowed("pt:nb_cols_portrait", 3), true, "project title allowed")
eq(core.settingAllowed("statistics.is_enabled", false), false, "statistics switch denied")
eq(core.settingAllowed("footer", 1), false, "whole footer table denied")
local src = core.menuOrderSource({ tools = { "lascisboard", "----------------------------", "bad id!" }, ["evil\"]"] = { "x" } })
eq(src:find("lascisboard", 1, true) ~= nil, true, "menu file has the item")
eq(src:find("bad id", 1, true), nil, "bad item dropped")
eq(src:find("evil", 1, true), nil, "bad list dropped")
local chunk = (loadstring or load)(src); eq(type(chunk), "function", "menu file is valid Lua")
eq(chunk().tools[2], "----------------------------", "separator kept")
-- sleep images
local dl, del = core.sleepPlan({ ["aa-1.jpg"] = 10, ["0ab-2.png"] = 5, ["mine.txt"] = 1 }, { { id = "aa-1", ext = "jpg", size = 10, url = "u1" }, { id = "bb-3", ext = "png", size = 7, url = "u2" } })
eq(#dl, 1, "one to download"); eq(dl[1].name, "bb-3.png", "new image"); eq(#del, 1, "one to delete"); eq(del[1], "0ab-2.png", "removed image")
local dl2 = core.sleepPlan({ ["aa-1.jpg"] = 9 }, { { id = "aa-1", ext = "jpg", size = 10 } })
eq(#dl2, 1, "size changed → download again")
-- streak
local today = os.time({ year = 2026, month = 10, day = 5, hour = 21 })
eq(core.streak({ ["2026-10-05"] = 5, ["2026-10-04"] = 30, ["2026-10-03"] = 2 }, today, 1), 3, "three days")
eq(core.streak({ ["2026-10-04"] = 30, ["2026-10-03"] = 2 }, today, 1), 2, "today not read yet: still counts to yesterday")
eq(core.streak({ ["2026-10-05"] = 5, ["2026-10-03"] = 9 }, today, 1), 1, "gap breaks it")
eq(core.streak({ ["2026-10-05"] = 5, ["2026-10-04"] = 9 }, today, 10), 0, "below the minimum")
local spring = os.time({ year = 2026, month = 3, day = 30, hour = 0, min = 30 })
eq(core.streak({ ["2026-03-30"] = 5, ["2026-03-29"] = 5, ["2026-03-28"] = 5 }, spring, 1), 3, "across the DST change")
eq(core.footerText(18, 30, 12), "18/30 min · 12 days", "footer")
eq(core.footerText(31, 30, 1), "Goal met · 31/30 min · 1 day", "footer goal met")
eq(core.newId(255, 1):match("^[%w%-]+$") ~= nil, true, "capture id shape")
eq(core.bookExtension("Book.kepub.epub"), "kepub.epub", "kepub kept whole")
eq(core.bookExtension("Book.EPUB"), "epub", "plain epub, lower case")
eq(core.bookExtension("Book.pdf"), "pdf", "pdf")
eq(core.bookExtension("noext"), "epub", "no extension -> epub")
eq(core.stripExtension("Rowling - Stone.kepub.epub"), "Rowling - Stone", "strip kepub")
eq(core.stripExtension("a.b.epub"), "a.b", "strip only the last")
-- lists (plugin 1.3): AutoWarmth's times and warmth, the margins
local N = core.NULL
local times = { 0.0, 5.5, 6.0, 6.5, 7.0, 13.0, 21.5, 22.0, 22.5, 23.0, 24.0 }
eq(core.settingAllowed("autowarmth_scheduler_times", times), true, "default times allowed")
eq(core.settingAllowed("autowarmth_scheduler_times", { N, 5.5, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23, N }), true, "times with holes allowed")
eq(core.settingAllowed("autowarmth_scheduler_times", { 0, 5.5, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23 }), false, "ten times refused")
eq(core.settingAllowed("autowarmth_scheduler_times", { 0, 7, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23, 24 }), false, "out of order refused")
eq(core.settingAllowed("autowarmth_scheduler_times", { 0, 5.5, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23, 30 }), false, "hour past 24:59 refused")
eq(core.settingAllowed("autowarmth_scheduler_times", { N, N, N, N, N, N, N, N, N, N, N }), false, "no time at all refused")
eq(core.settingAllowed("autowarmth_scheduler_times", "6:30"), false, "a string is not a list")
eq(core.settingAllowed("autowarmth_scheduler_times", { 0, 5.5, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23, 24, extra = 1 }), false, "extra keys refused")
eq(core.settingAllowed("autowarmth_scheduler_times", N), true, "reset allowed")
local warm = { 90, 90, 80, 60, 20, 20, 20, 60, 80, 90, 90 }
eq(core.settingAllowed("autowarmth_warmth", warm), true, "default warmth allowed")
eq(core.settingAllowed("autowarmth_warmth", { 1090, 90, 80, 60, 20, 20, 20, 60, 80, 90, 1090 }), true, "night mode +1000 allowed")
eq(core.settingAllowed("autowarmth_warmth", { 500, 90, 80, 60, 20, 20, 20, 60, 80, 90, 500 }), false, "between 100 and 1000 refused")
eq(core.settingAllowed("autowarmth_warmth", { 90, 90, 80, 60, 20, 20, 20, 60, 80, 90, 80 }), false, "not mirrored refused")
eq(core.settingAllowed("autowarmth_warmth", { 90, 90, 80, 60, 20, N, 20, 60, 80, 90, 90 }), false, "warmth has no holes")
eq(core.settingAllowed("autowarmth_warmth", { 90.5, 90, 80, 60, 20, 20, 20, 60, 80, 90, 90.5 }), false, "warmth is whole")
eq(core.settingAllowed("copt_h_page_margins", { 15, 15 }), true, "margins")
eq(core.settingAllowed("copt_h_page_margins", { 15, 150 }), false, "margin over 140 refused")
eq(core.settingAllowed("copt_word_spacing", { 100, 90 }), true, "word spacing")
eq(core.settingAllowed("copt_word_spacing", { 100, 20 }), false, "reduction under 25 refused (per position)")
local stored = core.listValue({ N, 5.5, 6, 6.5, 7, 13, 21.5, 22, 22.5, 23, N }, core.listSpec("autowarmth_scheduler_times"))
eq(stored[1], nil, "null becomes a hole"); eq(stored[2], 5.5, "value kept"); eq(stored[11], nil, "last hole")
local rep = core.listReport(stored, core.listSpec("autowarmth_scheduler_times"), "NULL")
eq(#rep, 11, "report has every item"); eq(rep[1], "NULL", "hole reported as null"); eq(rep[5], 7, "time reported")
eq(core.listReport("x", core.listSpec("autowarmth_scheduler_times"), "NULL"), nil, "not a table: nothing reported")
eq(core.listSpec("cre_font"), nil, "a plain key has no list spec")
eq(core.settingAllowed("cre_font", "Noto Sans"), true, "font name allowed")
-- fonts
local fr = core.fontReport({ "Noto Serif", "FreeSans", "Noto Serif", "" }, {
  ["./fonts/noto/NotoSans-Bold.ttf"] = { { name = "Noto Sans", bold = true } },
  ["./fonts/noto/NotoSans-Regular.ttf"] = { { name = "Noto Sans" } },
  ["/mnt/onboard/fonts/broken.ttf"] = {},
})
eq(#fr.faces, 2, "faces deduplicated, empty dropped"); eq(fr.faces[1], "FreeSans", "faces sorted")
eq(#fr.files, 2, "files without info dropped"); eq(fr.files[1].file, "./fonts/noto/NotoSans-Bold.ttf", "files sorted by path")
eq(fr.files[1].bold, true, "bold kept"); eq(fr.files[2].italic, false, "italic false")
eq(#core.fontReport({ "a", "b", "c" }, {}, 2).faces, 2, "faces capped")
print(("test-lbcore: %d checks passed"):format(n))
